#! /bin/ksh --login

#PBS -e /scratch3/NCEPDEV/stmp1/Bin.Li/rt_53202/cfsr%20150401_5days_nems_gsm%slg%T126_cice%0.24_hycom%0.24/err
#PBS -o /scratch3/NCEPDEV/stmp1/Bin.Li/rt_53202/cfsr%20150401_5days_nems_gsm%slg%T126_cice%0.24_hycom%0.24/out
#PBS -N rt_53202_1
#PBS -A omd
#PBS -q batch
#PBS -l procs=172
#PBS -l walltime=00:120:00
#PBS -W umask=027

set -aeux
export MPI_GROUP_MAX=96
# ulimit -n 16000
# Enable Fortran RTL core dumps for severe run time failures
# export decfort_dump_flag=y

export SCHEDULER=pbs

export FIXGLOBAL=/scratch4/NCEPDEV/global/save/Shrinivas.Moorthi/para/fix/fix_am

cd /scratch3/NCEPDEV/stmp1/Bin.Li/rt_53202/cfsr%20150401_5days_nems_gsm%slg%T126_cice%0.24_hycom%0.24

echo "Model started:  " `date`

#module load intel
#module load mpt
#module load adaptive

export TASKSIZE=172

/scratch3/NCEPDEV/stmp1/Bin.Li/rt_53202/cfsr%20150401_5days_nems_gsm%slg%T126_cice%0.24_hycom%0.24/gfs_fcst_run

echo "Model ended:    " `date`

exit
