#!/bin/ksh
#BSUB -e /ptmp/Bin.Li/rt_172882/cfsr%20150401_30day_nems_gsm%slg%T126_cice%0.24_hycom%0.24/err
#BSUB -o /ptmp/Bin.Li/rt_172882/cfsr%20150401_30day_nems_gsm%slg%T126_cice%0.24_hycom%0.24/out
#BSUB -J rt_172882_1
#BSUB -q 
#BSUB -P omd
#BSUB -n 188
#BSUB -x
#BSUB -W 00:25
set -x
export OMP_NUM_THREADS=1
#export MP_EUIDEVICE=sn_all
#export MP_EUILIB=us
#if [ $OMP_NUM_THREADS -gt 1 ] ; then
#  export MP_TASK_AFFINITY=cpu:1
#else
#  export MP_TASK_AFFINITY=core
#fi
export MP_EUIDEVELOP=min
#export KMP_STACKSIZE=1024m
#export F_UFMTENDIAN=big
#export MPICH_ALLTOALL_THROTTLE=0
#export MP_SINGLE_THREAD=yes
#export MP_EAGER_LIMIT=65536
#export MP_USE_BULK_XFER=yes
#export MP_COLLECTIVE_OFFLOAD=yes
#export MP_SHARED_MEMORY=no
export MP_MPILIB=mpich2
export MP_LABELIO=yes
export MP_STDOUTMODE=unordered


cd /ptmp/Bin.Li/rt_172882/cfsr%20150401_30day_nems_gsm%slg%T126_cice%0.24_hycom%0.24

echo "Model started:  " `date`

#export TASKSIZE=188

# ulimit -n 16000
# Enable Fortran RTL core dumps for severe run time failures
# export decfort_dump_flag=y

env
/ptmp/Bin.Li/rt_172882/cfsr%20150401_30day_nems_gsm%slg%T126_cice%0.24_hycom%0.24/gfs_fcst_run

echo "Model ended:    " `date`

exit
