#!/bin/sh -l
#PBS -o out
#PBS -e err
#PBS -N rt_94195_1
#PBS -A omd
#PBS -q debug
#PBS -d .
#PBS -l procs=48
#PBS -l walltime=00:30:00

set -eux

export MPI_TYPE_DEPTH=20
export OMP_NUM_THREADS=1
export ESMF_RUNTIME_COMPLIANCECHECK=OFF:depth=4
#ulimit -s unlimited

#source /apps/lmod/lmod/init/sh
source /scratch3/NCEPDEV/stmp1/Bin.Li/UGCS-Seasonal/trunk/NEMS/src/conf/modules.nems
module list

pwd 

echo "Model started:  " `date`

#mpirun -prepend-rank -np $PBS_NP ./NEMS.x
mpirun  -prepend-rank -np $PBS_NP ./NEMS.x

echo "Model ended:    " `date`

exit
